### ISSUE TITLE
Archive project plugin only work with rush version 5.57.1

### ISSUE THREAD

**Issue by lianghx-319** [bytesfriends/rush-plugins#11]
After I upgraded to rush 5.61.3, this plugin always throw error `Can not load rush configuration`

**Comment by lianghx-319** [comment]
I used pnpm overrides work around it temporarily

**Comment by chengcyber** [comment]
@lianghx-319 

🚀  `rush-archive-project-plugin@1.1.2` released. Tested locally with a project using `rush@5.61.3`.
