### ISSUE TITLE
Error occur after upgrade rush to 5.59.2

### ISSUE THREAD

**Issue by lianghx-319** [bytesfriends/rush-plugins#6]
![image](https://user-images.githubusercontent.com/27187946/148867962-f95990d6-942c-4592-a81f-9af145d89961.png)

**Comment by chengcyber** [comment]
It seems to me this is a regression from rush side. See https://github.com/microsoft/rushstack/issues/3155 for detail.

**Comment by octogonz** [comment]
This is fixed in the latest release 5.61.1.  5.60.0 introduces a breaking change for the build cache, so we have backported this fix as 5.60.1 and 5.59.3.
